server:
  port: 8083
spring:
  application:
    name: mall-service-file
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#mybatis:
#  mapper-locations: mappers/*.xml
#  type-aliases-package: com.mall.goods.pojo
