server:
  port: 18081
spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.35.133:3306/mall_goods?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 0
    host: 47.110.35.133
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-midle: 8
        max-wait: 100ms
        min-idle: 0
    timeout: 5000ms

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

#mybatis:
#  mapper-locations: mappers/*.xml
#  type-aliases-package: com.mall.goods.pojo
